### ISSUE TITLE
Crash with underground pipes nearby

### ISSUE THREAD

**Issue by Shtriger** [PlexPt/small-factorio-mods#3]
keeps crashing with the following when trying to place with pipes (underground pipes) nearby.

Die Mod BeltRouter Lite (2.4.1) hat einen Fehler verursacht, der nicht behoben werden kann.
Bitte informiere den Autor der Mod über diesen Fehler.

Error while running event BeltRouter-lite::on_nth_tick(1)
Entity is not pump or offshore-pump.
stack traceback:
	[C]: in function '__index'
	__BeltRouter-lite__/path_find/entity_routing_attribute.lua:145: in function 'from'
	__BeltRouter-lite__/control.lua:161: in function 'getEntityFunc'
	__BeltRouter-lite__/transport_line_connector.lua:51: in function 'neighboringEntities'
	__BeltRouter-lite__/transport_line_connector.lua:239: in function 'testCanPlace'
	__BeltRouter-lite__/transport_line_connector.lua:199: in function 'surroundingCandidates'
	__BeltRouter-lite__/transport_line_connector.lua:163: in function 'task'
	__BeltRouter-lite__/async_task.lua:43: in function 'resolveOneTask'
	__BeltRouter-lite__/async_task.lua:36: in function <__BeltRouter-lite__/async_task.lua:35>

**Comment by PlexPt** [comment]
fixed
