### ISSUE TITLE
Jinx character mod doesn't work

### ISSUE THREAD

**Issue by jigsaw3xD** [PlexPt/small-factorio-mods#8]
Jinx character mod doesn't work. No errors or crashes, the updated character model just doesn't show up. Tried it on a completely vanilla modlist as well (with only 2 other mods required to run it). I have a SA version of the game.

**Comment by PlexPt** [comment]
post on mod portal

**Comment by PlexPt** [comment]
install  minime

**Comment by jigsaw3xD** [comment]
> install minime

it works now. tho there's a new bug, the model is way higher than it should be, on this screenshot i getting moved by the belt as if  a stand on it even visually tho im not standing on it.

![MUwW8c5iLa](https://github.com/user-attachments/assets/d3f9b583-3486-40c3-88d0-e3fbd7584aa2)

> post on mod portal

i don't have a mod portal account, i play on pirated

**Comment by jigsaw3xD** [comment]
she's even higher on this preview

![URFc4t3pqF](https://github.com/user-attachments/assets/ae92fb54-e21f-43c2-882f-35d3ad539804)
